name: urban-gee-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - numpy
  - pandas
  - scipy
  - matplotlib
  - geopandas
  - rasterio
  - scikit-learn
  - statsmodels
  - pyproj
  - googledrivedownloader
  - spyder
  - earthengine-api
  - dask[dataframe]
  - openpyxl
  - pip
  - seaborn
  - pip:
    - pycountry_convert
  